lub zmodyfikują moje udostępnione elementy",
  "rnsettingsMassDeleteNotification": "Powiadom mnie o usunięciu dużej liczby plików w chmurze",
  "rnsettingsLocalMassDeleteSettingsCheckbox": "Powiadom mnie, zanim wiele plików usuniętych na moim komputerze zostanie usuniętych z chmury",
  "rnsettingsUnavailableDueToPolicy": "To ustawienie jest niedostępne ze względu na zasady organizacji.",
  "aboutDialogDeviceidLabel": "Identyfikator urządzenia w usłudze OneDrive:",
  "aboutDialogDeviceidCopy": "Kopiuj do schowka",
  "aboutDialogDeviceidCopyShort": "Kopiuj",
  "aboutDialogDeviceidCopiedShort": "Skopiowano!",
  "aboutDialogInfoCopied": "Skopiowano do schowka identyfikator i wersję urządzenia w usłudze OneDrive",
  "aboutDialogOnedriveInfoLabel": "Informacje o usłudze OneDrive",
  "aboutDialogOnedriveInfoToggleHint": "Przełącza widok identyfikatora i wersji urządzenia w usłudze OneDrive",
  "aboutDialogVersionLabel": "Wersja usługi OneDrive:",
  "aboutDialogRelatedLinks": "Linki pokrewne",
  "aboutDialogCopyButtonHint": "Kopiuje identyfikator urządzenia usługi OneDrive i numer wersji.",
  "settingsNotificationTab": "Powiadomienia",
  "settingsOnThisDayMemoriesNotification": "Powiadom mnie, gdy wspomnienia obszaru „W tym dniu” są dostępn